# Generated by Django 5.2.5 on 2025-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_audio_message_deleted_for_everyone_and_more'),
    ]

    operations = [
        # Rename the old 'receiver' field to 'received'
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='received',
        ),
        # Add the new image field for sending photos
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='chat_images/', blank=True, null=True),
        ),
    ]
