# Generated by Django 5.2.5 on 2025-12-13 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_phone_number_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_for_everyone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_for_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_for_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='core_messag_sender__e44d4b_idx'),
        ),
    ]
